[package]
name = "send-vrc-desktop"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.55"
axum = "0.4.8"
time = { version = "0.3.7", features = ["local-offset"] }
tokio = { version = "1.17.0", features = ["full"] }
serde = { version = "1.0.136", features = ["derive"] }
clipboard-win = "4.4.1"
windows = { version = "0.33.0", features = ["alloc", "Win32_Foundation", "Win32_UI_Input_KeyboardAndMouse", "Win32_UI_WindowsAndMessaging"] }
