name: Release

on:
  push:
    tags:
      - "v[0-9]+.[0-9]+.[0-9]+*"

env:
  CARGO_TERM_COLOR: always

jobs:
  get-release-version:
    runs-on: ubuntu-latest
    steps:
      - run: echo "RELEASE_VERSION=${GITHUB_REF#refs/tags/v}" >> "$GITHUB_ENV"
    outputs:
      release_version: ${{ env.RELEASE_VERSION }}

  build-and-release:
    runs-on: windows-latest
    needs: ["get-release-version"]
    steps:
      - uses: actions/checkout@v3

      - uses: ./.github/actions/cargo-cache

      - name: Build
        run: cargo build --release --verbose

      - name: Archive to zip
        run: |
          New-Item -ItemType Directory dist
          Compress-Archive -Path target/release/send-vrc-desktop.exe -DestinationPath dist/send-vrc-desktop-${{ needs.get-release-version.outputs.release_version }}-x86_64-pc-windows-msvc.zip

      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          files: dist/send-vrc-desktop-${{ needs.get-release-version.outputs.release_version }}-x86_64-pc-windows-msvc.zip
          prerelease: ${{ contains(github.ref, '-beta') }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
